#pragma clang diagnostic ignored   "-Wunknown-pragmas"

#pragma clang diagnostic warning   "-Wall"
#pragma clang diagnostic warning   "-Weffc++"
#pragma clang diagnostic warning   "-Wextra"

#pragma clang diagnostic warning   "-Wcast-qual"
#pragma clang diagnostic warning   "-Wchar-subscripts"
#pragma clang diagnostic warning   "-Wconversion"
#pragma clang diagnostic warning   "-Wctor-dtor-privacy"
#pragma clang diagnostic warning   "-Wempty-body"
#pragma clang diagnostic warning   "-Wfloat-equal"
#pragma clang diagnostic warning   "-Wformat"
#pragma clang diagnostic warning   "-Wformat-nonliteral"
#pragma clang diagnostic warning   "-Wformat-security"
#pragma clang diagnostic warning   "-Wmissing-declarations"
#pragma clang diagnostic warning   "-Wnon-virtual-dtor"
#pragma clang diagnostic warning   "-Woverloaded-virtual"
#pragma clang diagnostic warning   "-Wpacked"
#pragma clang diagnostic warning   "-Wpointer-arith"
#pragma clang diagnostic warning   "-Wredundant-decls"
#pragma clang diagnostic warning   "-Wshadow"
#pragma clang diagnostic warning   "-Wsign-promo"
#pragma clang diagnostic warning   "-Wstrict-aliasing"
#pragma clang diagnostic warning   "-Wstrict-overflow"
#pragma clang diagnostic warning   "-Wswitch-default"
#pragma clang diagnostic warning   "-Wswitch-enum"
#pragma clang diagnostic warning   "-Wunused"

#pragma clang diagnostic warning   "-Wunknown-pragmas"
